name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World, github actions"
      - name: Print Goodbye
        run: echo "DONE! Goodbye github actions"
